// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/CoreumFoundation/coreumbridge-xrpl/relayer/xrpl (interfaces: RPCTxProvider,MetricRegistry)

// Package xrpl_test is a generated GoMock package.
package xrpl_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	data "github.com/rubblelabs/ripple/data"

	xrpl "github.com/CoreumFoundation/coreumbridge-xrpl/relayer/xrpl"
)

// MockRPCTxProvider is a mock of RPCTxProvider interface.
type MockRPCTxProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRPCTxProviderMockRecorder
}

// MockRPCTxProviderMockRecorder is the mock recorder for MockRPCTxProvider.
type MockRPCTxProviderMockRecorder struct {
	mock *MockRPCTxProvider
}

// NewMockRPCTxProvider creates a new mock instance.
func NewMockRPCTxProvider(ctrl *gomock.Controller) *MockRPCTxProvider {
	mock := &MockRPCTxProvider{ctrl: ctrl}
	mock.recorder = &MockRPCTxProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCTxProvider) EXPECT() *MockRPCTxProviderMockRecorder {
	return m.recorder
}

// AccountTx mocks base method.
func (m *MockRPCTxProvider) AccountTx(arg0 context.Context, arg1 data.Account, arg2, arg3 int64, arg4 map[string]interface{}) (xrpl.AccountTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountTx", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(xrpl.AccountTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountTx indicates an expected call of AccountTx.
func (mr *MockRPCTxProviderMockRecorder) AccountTx(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountTx", reflect.TypeOf((*MockRPCTxProvider)(nil).AccountTx), arg0, arg1, arg2, arg3, arg4)
}

// LedgerCurrent mocks base method.
func (m *MockRPCTxProvider) LedgerCurrent(arg0 context.Context) (xrpl.LedgerCurrentResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LedgerCurrent", arg0)
	ret0, _ := ret[0].(xrpl.LedgerCurrentResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LedgerCurrent indicates an expected call of LedgerCurrent.
func (mr *MockRPCTxProviderMockRecorder) LedgerCurrent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LedgerCurrent", reflect.TypeOf((*MockRPCTxProvider)(nil).LedgerCurrent), arg0)
}

// MockMetricRegistry is a mock of MetricRegistry interface.
type MockMetricRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockMetricRegistryMockRecorder
}

// MockMetricRegistryMockRecorder is the mock recorder for MockMetricRegistry.
type MockMetricRegistryMockRecorder struct {
	mock *MockMetricRegistry
}

// NewMockMetricRegistry creates a new mock instance.
func NewMockMetricRegistry(ctrl *gomock.Controller) *MockMetricRegistry {
	mock := &MockMetricRegistry{ctrl: ctrl}
	mock.recorder = &MockMetricRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricRegistry) EXPECT() *MockMetricRegistryMockRecorder {
	return m.recorder
}

// SetXRPLAccountFullHistoryScanLedgerIndex mocks base method.
func (m *MockMetricRegistry) SetXRPLAccountFullHistoryScanLedgerIndex(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetXRPLAccountFullHistoryScanLedgerIndex", arg0)
}

// SetXRPLAccountFullHistoryScanLedgerIndex indicates an expected call of SetXRPLAccountFullHistoryScanLedgerIndex.
func (mr *MockMetricRegistryMockRecorder) SetXRPLAccountFullHistoryScanLedgerIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetXRPLAccountFullHistoryScanLedgerIndex", reflect.TypeOf((*MockMetricRegistry)(nil).SetXRPLAccountFullHistoryScanLedgerIndex), arg0)
}

// SetXRPLAccountRecentHistoryScanLedgerIndex mocks base method.
func (m *MockMetricRegistry) SetXRPLAccountRecentHistoryScanLedgerIndex(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetXRPLAccountRecentHistoryScanLedgerIndex", arg0)
}

// SetXRPLAccountRecentHistoryScanLedgerIndex indicates an expected call of SetXRPLAccountRecentHistoryScanLedgerIndex.
func (mr *MockMetricRegistryMockRecorder) SetXRPLAccountRecentHistoryScanLedgerIndex(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetXRPLAccountRecentHistoryScanLedgerIndex", reflect.TypeOf((*MockMetricRegistry)(nil).SetXRPLAccountRecentHistoryScanLedgerIndex), arg0)
}
