[package]
name = "coreumbridge-xrpl"
version = "0.1.0"
authors = ["Coreum"]
edition = "2021"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
base64 = "0.21.4"
coreum-wasm-sdk = "0.2.0"
cosmwasm-schema = "1.4.0"
cosmwasm-std = "1.4.0"
cw-ownable = "0.5.1"
cw-storage-plus = "1.1.0"
cw-utils = "1.0.1"
cw2 = "1.1.0"
sha2 = "0.10.7"
thiserror = "1.0.48"

[dev-dependencies]
coreum-test-tube = "3.0.0"
