{
 "title": "Coreum bridge XRPL relayer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "relayer_coreum_address",
    "label": "Relayer coreum address",
    "query": {
     "query": "label_values(relayer_coreum_address)"
    }
   },
   {
    "name": "xrpl_currency_issuer",
    "label": "XRPL currency/issuer",
    "query": {
     "query": "label_values(xrpl_currency_issuer)"
    }
   },
   { "name": "coreum_denom", "label": "Corem denom", "query": { "query": "label_values(coreum_denom)" } }
  ]
 },
 "panels": [
  { "title": "State monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "XRPL bridge account balances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "xrpl_bridge_account_balances{xrpl_currency_issuer=~\"$xrpl_currency_issuer\"}",
     "legendFormat": "{{xrpl_currency_issuer}}"
    }
   ]
  },
  {
   "title": "Contract balances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "contract_balances{xrpl_currency_issuer=~\"$xrpl_currency_issuer\", coreum_denom=~\"$coreum_denom\"}",
     "legendFormat": "{{coreum_denom}} | {{xrpl_currency_issuer}}"
    }
   ]
  },
  {
   "title": "XRPL tokens supply on Coreum",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "xrpl_tokens_coreum_supply{xrpl_currency_issuer=~\"$xrpl_currency_issuer\", coreum_denom=~\"$coreum_denom\"}",
     "legendFormat": "{{coreum_denom}} | {{xrpl_currency_issuer}}"
    }
   ]
  },
  {
   "title": "XRPL bridge account XRP self balance ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(xrpl_bridge_account_balances{xrpl_currency_issuer=\"XRP/rrrrrrrrrrrrrrrrrrrrrhoLvTp\"} - on () xrpl_tokens_coreum_supply{xrpl_currency_issuer=\"XRP/rrrrrrrrrrrrrrrrrrrrrhoLvTp\"} - on () xrpl_bridge_account_reserves)",
     "legendFormat": "Balance (XRP)"
    }
   ]
  },
  {
   "title": "XRPL bridge account XRP reserves",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "xrpl_bridge_account_reserves", "legendFormat": "reserves (XRP)" }
   ]
  },
  {
   "title": "XRPL base fee",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    { "expr": "contract_config_xrpl_base_fee", "legendFormat": "Contract XRPL base fee" },
    { "expr": "xrpl_chain_base_fee", "legendFormat": "XRPL chain base fee" }
   ]
  },
  {
   "title": "Bridge state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "bridge_state",
     "legendFormat": "Bridge state (1 - active, 0 - halted)"
    }
   ]
  },
  { "title": "Processing monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Pending operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "targets": [
    { "expr": "pending_operations", "legendFormat": "{{operation_id}}" }
   ]
  },
  {
   "title": "Transaction evidences",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "targets": [
    { "expr": "transaction_evidences", "legendFormat": "{{evidence_hash}}" }
   ]
  },
  {
   "title": "Free tickets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "targets": [
    { "expr": "free_contract_tickets", "legendFormat": "Free contract tickets" },
    { "expr": "free_xrpl_tickets", "legendFormat": "Free XRPL tickets" }
   ]
  },
  {
   "title": "XRPL account scanning ledger ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "xrpl_account_full_history_scan_ledger_index",
     "legendFormat": "Full history"
    },
    {
     "expr": "xrpl_account_recent_history_scan_ledger_index",
     "legendFormat": "Recent history"
    }
   ]
  },
  {
   "title": "Errors increase 5m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(relayer_errors_total[5m])",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Relayers monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Relayer balance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "relayer_balances{relayer_coreum_address=~\"$relayer_coreum_address\"}",
     "legendFormat": "{{relayer_coreum_address}}"
    }
   ]
  },
  {
   "title": "Relayer 24h activity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "relayer_activity{relayer_coreum_address=~\"$relayer_coreum_address\"}",
     "legendFormat": "{{relayer_coreum_address}} | {{action}} "
    }
   ]
  },
  {
   "title": "Malicious behaviour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "targets": [
    { "expr": "malicious_behaviour", "legendFormat": "{{malicious_behaviour_key}}" }
   ]
  },
  {
   "title": "Relayer version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "relayer_version{relayer_coreum_address=~\"$relayer_coreum_address\"}",
     "legendFormat": "{{relayer_coreum_address}} | {{version}} "
    }
   ]
  }
 ]
}