name: contract-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Lint contract
        run: make lint-contract
      - name: Build contract
        run: make build-contract
      - name: Run tests
        run: make test-contract
