name: contract-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up cargo/wasm cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            contract/target/
          key: ${{ runner.os }}-cargo-wasm-cache-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Lint contract
        run: make lint-contract
      - name: Build contract
        run: make build-contract
      - name: Run tests
        run: make test-contract
