name: relayer-ci
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        ci_step: [
          "lint",
          "test",
          "integration tests contract",
          "integration tests processes",
          "integration tests xrpl",
        ]
        include:
          - ci_step: "lint"
            command: make lint
          - ci_step: "test"
            command: make test fuzz-test
          - ci_step: "integration tests contract"
            command: make integration-tests-contract
          - ci_step: "integration tests processes"
            command: make integration-tests-processes
          - ci_step: "integration tests xrpl"
            command: make integration-tests-xrpl

    runs-on: self-hosted
    steps:
      - name: Go version used to build builder
        run: go version
      - name: Checkout coreumbridge-xrpl
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run ${{ matrix.ci_step }}
        run: ${{ matrix.command }}
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
