name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout coreumbridge-xrpl-relayer
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build binaries
        run: make release
      - name: Build and publish images
        run: make release-images
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=release::true
          fi
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+-rc.*$ ]]; then
              echo ::set-output name=release_candidate::true
          fi
      - name: Link released binaries under right names
        run: |
          ln bin/.cache/coreumbridge-xrpl-relayer/docker.linux.amd64/bin/coreumbridge-xrpl-relayer coreumbridge-xrpl-relayer-linux-amd64
          ln bin/.cache/coreumbridge-xrpl-relayer/docker.linux.arm64/bin/coreumbridge-xrpl-relayer coreumbridge-xrpl-relayer-linux-arm64
          ln bin/.cache/coreumbridge-xrpl-relayer/docker.darwin.amd64/bin/coreumbridge-xrpl-relayer coreumbridge-xrpl-relayer-darwin-amd64
          ln bin/.cache/coreumbridge-xrpl-relayer/docker.darwin.arm64/bin/coreumbridge-xrpl-relayer coreumbridge-xrpl-relayer-darwin-arm64
          sha256sum coreumbridge-xrpl-relayer-* > checksums.txt
      - name: Create release
        if: steps.check-tag.outputs.release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: |
            coreumbridge-xrpl-relayer-linux-amd64
            coreumbridge-xrpl-relayer-linux-arm64
            coreumbridge-xrpl-relayer-darwin-amd64
            coreumbridge-xrpl-relayer-darwin-arm64
            checksums.txt
      - name: Create release candidate
        if: steps.check-tag.outputs.release_candidate == 'true'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          generate_release_notes: true
          files: |
            coreumbridge-xrpl-relayer-linux-amd64
            coreumbridge-xrpl-relayer-linux-arm64
            coreumbridge-xrpl-relayer-darwin-amd64
            coreumbridge-xrpl-relayer-darwin-arm64
            checksums.txt
